FROM python:3.13-slim 

# Install UV 
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/ 

WORKDIR /app 

#Copy dependency files 
COPY pyproject.toml . 

# Install dependencies
RUN uv pip install --system -r pyproject.toml 

# Copy app code
COPY ingestion.py . 

CMD ["python", "ingestion.py"]